feat(l2): add prover client to integration test (#2291)
**Motivation**

The integration test is being run without a prover client and bypassing
verification. We want this test to run every component of the L2.

**Description**

- executes the prover client together with the integration test (ideally
we would run the prover in a docker container but some backends like SP1
start a container to execute the final phase of proving, a container
can't create another one without being privileged, so for now we run the
prover client as another process).
- refactors the state reconstruction test out of the integration test
- defines a workflow to run the integration test on each PR push using
the `exec` backend
- defines a workflow to run the integration test on main using the `sp1`
backend
- adds docker layer caching using `bake`, defines new "Docker bake" job
- removes any reference to zkvm-specific env variables used for
bypassing verification or mock proving
- removes the prover server dev mode loop. Now "dev mode" refers to
using the `exec` backend. This and the previous point make sure there's
always a prover client running and executing blocks, even if it's not
generating proofs.

Closes #2224

---------

Co-authored-by: fborello-lambda <federicoborello@lambdaclass.com>
Co-authored-by: Federico Borello <156438142+fborello-lambda@users.noreply.github.com>
Co-authored-by: Javier Chatruc <jrchatruc@gmail.com>
Co-authored-by: Javier Rodríguez Chatruc <49622509+jrchatruc@users.noreply.github.com>

diff --git a/crates/l2/Makefile b/crates/l2/Makefile
--- a/crates/l2/Makefile
+++ b/crates/l2/Makefile
@@ -167,11 +167,19 @@ down-l2: ## 🛑 Shuts down the L2 Lambda ethrex Client
 
 restart-l2: down-l2 rm-db-l2 init-l2 ## 🔄 Restarts the L2 Lambda ethrex Client
 
-init-prover: ## 🚀 Initializes the Prover
-	@if [ -z "$$T" ]; then \
-		echo "Error: ProverType (T) is missing. Running in exec mode."; \
-		echo "You can provide it as an argument:"; \
-		echo "make init-prover T=<prover_type: (risc0, sp1, pico)> <G=true>."; \
+init-prover: ../../target/release/ethrex_prover ## 🚀 Initializes the Prover
+	CONFIGS_PATH=${ethrex_L2_CONFIGS_PATH} \
+	PROVER_CLIENT_CONFIG_FILE=${ethrex_L2_PROVER_CLIENT_CONFIG_FILE} \
+	PROVER_ENV_FILE=${PROVER_ENV_FILE} \
+	../../target/release/ethrex_prover
+
+build-prover: ../../target/release/ethrex_prover
+
+../../target/release/ethrex_prover:
+	@if [ -z "$$PROVER" ]; then \
+		echo "Error: ProverType (PROVER) is missing. Running in exec mode."; \
+		echo "Please provide it as an argument:"; \
+		echo "make init-prover PROVER=<prover_type: (risc0, sp1, pico)> <G=true>"; \
 		echo "The prover can also be run with GPU (G)"; \
 	fi; \
 
@@ -184,41 +192,36 @@ init-prover: ## 🚀 Initializes the Prover
 	CONFIGS_PATH=${ethrex_L2_CONFIGS_PATH} \
 	PROVER_CLIENT_CONFIG_FILE=${ethrex_L2_PROVER_CLIENT_CONFIG_FILE} \
 	PROVER_ENV_FILE=${PROVER_ENV_FILE} \
-	cargo run --release --features "$$T$$GPU,l2" \
-	--manifest-path ./prover/Cargo.toml \
-	--bin ethrex_prover -- $$T
+	RUSTFLAGS='-C target-cpu=native' \
+	cargo build --release --features "$$PROVER$$GPU,l2" \
+	--manifest-path ./prover/Cargo.toml  \
+	--bin ethrex_prover
 
 rm-db-l2: ## 🛑 Removes the DB used by the L2
 	cargo run --release --manifest-path ../../Cargo.toml --bin ethrex --features l2 -- l2 removedb --datadir ${ethrex_L2_DEV_LIBMDBX} --force
 
-# Testing
-# cargo test l2 will match tests that has l2 in the function.
-# Tests are at `crates/l2/tests/tests.rs`
-# https://doc.rust-lang.org/book/ch11-02-running-tests.html#filtering-to-run-multiple-tests
-ci_test: ## 🚧 Runs the L2's integration test, used by the github's CI
-	@echo "\n\033[0;33mWARNING: \033[0m Running the tests inside docker takes \033[1mA LOT\033[0m of time. If possible (especially when running the tests locally), consider running the tests with the 'make test' directive\n"
+test: ## 🚧 Runs the L2's integration test, run `make init` and in a new terminal make test
+	cargo test l2 --release -- --nocapture --test-threads=1 || (echo "The tests have failed.\n Is the L2 running? To start it, run:\n make rm-db-l1; make rm-db-l2; make restart" ; exit 1)
 
+integration-test: rm-db-l2 rm-db-l1
 	# We create an empty .env file simply because if the file
 	# does not exists, the container fails to write to it.
 	touch .env
-	# Integration tests
 	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f ${ethrex_L2_DOCKER_COMPOSE_PATH} down
-	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f ${ethrex_L2_DOCKER_COMPOSE_PATH} up -d --build
-	cargo test l2 --release -- --nocapture --test-threads=1
-	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f ${ethrex_L2_DOCKER_COMPOSE_PATH} down
+	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f ${ethrex_L2_DOCKER_COMPOSE_PATH} up --detach --build
+	RUST_LOG=info,ethrex_prover_lib=debug make init-prover & cargo test l2 --release -- --nocapture --test-threads=1
+	killall ethrex_prover
 
-	# State reconstruction tests
-	rm -rf $$PWD/store
+# State reconstruction tests
+state-diff-test:
+	touch .env
 	cargo run --release --manifest-path ../../cmd/ethrex_l2/Cargo.toml --bin ethrex_l2 -- config create ci --default
 	cargo run --release --manifest-path ../../cmd/ethrex_l2/Cargo.toml --bin ethrex_l2 -- config set ci
 	cargo run --release --manifest-path ../../cmd/ethrex_l2/Cargo.toml --bin ethrex_l2 -- stack reconstruct -g ../../test_data/genesis-l2.json -b ../../test_data/blobs/ -s $$PWD/store -c 0x0007a881CD95B1484fca47615B64803dad620C8d
 	cargo b --manifest-path ../../Cargo.toml --release
-	make init-l2-no-metrics ethrex_L2_DEV_LIBMDBX=$$PWD/store 2>&1 >/dev/null &
+	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f docker-compose-l2.yaml -f docker-compose-l2-store.overrides.yaml down
+	CI_ETHREX_WORKDIR=${CI_ETHREX_WORKDIR} docker compose -f docker-compose-l2.yaml -f docker-compose-l2-store.overrides.yaml up --detach
 	cargo test state_reconstruct --release
-
-test: ## 🚧 Runs the L2's integration test, run `make init` and in a new terminal make test
-	cargo test l2 --release -- --nocapture --test-threads=1 || (echo "The tests have failed.\n Is the L2 running? To start it, run:\n make rm-db-l1; make rm-db-l2; make restart" ; exit 1)
-
 
 # Purge L2's state
 UNAME_S:=$(shell uname -s)
