ci(levm): silence messages (#1837)
**Motivation**

We would like to suppress certain messages and run the hive tests in the
`ci_levm.yaml` file.

**Description**

Silence LEVM EF-TESTS messages if all of them pass.
- Send a message to slack only if we don't have a `100%`
- Create the PR comment with the Summary only if we don't have a `100%`
- If we create the comment, update it later with the message `All
EF-TESTS pass.` if the bug is fixed within the PR.

Silence LEVM Hive Tests messages if no differences were found with
respect to revm.
- Add Hive Tests check to LEVM CI &rarr; fails if differences were found
- Send a message to slack only if we `do` find differences.

diff --git a/.github/workflows/ci_levm.yaml b/.github/workflows/ci_levm.yaml
--- a/.github/workflows/ci_levm.yaml
+++ b/.github/workflows/ci_levm.yaml
@@ -2,9 +2,9 @@ name: LEVM
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "**" ]
+    branches: ["**"]
     paths:
       - "crates/vm/levm/**"
 
@@ -18,8 +18,8 @@ env:
 
 jobs:
   ef-test:
-    # "Integration Test" is a required check, don't change the name
-    name: Integration Test
+    if: ${{ github.event_name != 'merge_group' }}
+    name: EF Tests Check
     runs-on: ubuntu-latest
     steps:
       - name: Checkout sources
@@ -58,6 +58,78 @@ jobs:
               echo "Percentage is not 100%."
               exit 1
           fi
+
+  hive-report-creation:
+    uses: ./.github/workflows/common_hive_reports.yaml
+    with:
+      evm: levm
+      job_type: trigger
+
+  # Check we don't have a regression against main
+  hive-test:
+    if: ${{ github.event_name != 'merge_group' }}
+    name: Hive Tests Check
+    needs: hive-report-creation
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+
+      - name: Download results (pr)
+        uses: actions/download-artifact@v4
+        with:
+          name: results_levm_trigger.md
+
+      - name: Rename result (1)
+        run: cp results.md results_levm.md
+
+      - name: Download results (main)
+        uses: actions/download-artifact@v4
+        with:
+          name: results_levm_daily.md
+        # If we don't have the file it will use the result(1) file
+        continue-on-error: true
+
+      - name: Rename result (2)
+        run: cp results.md results_levm_daily.md
+
+      - name: Create diff message
+        run: |
+          bash .github/scripts/hive_levm_revm_diff.sh results_levm_daily.md results_levm.md >> diff.md
+          cat diff.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Check Regression
+        run: |
+          if grep -q "No differences found" diff.md; then
+            echo "No differences found."
+          elif ! grep -q "regression" diff.md; then
+            echo "No regression found."
+          else
+            echo "Differences found."
+            exit 1
+          fi
+
+  # The purpose of this job is to add it as a required check in GitHub so that we don't have to add every individual job as a required check
+  all-tests:
+    # "Integration Test" is a required check, don't change the name
+    name: Integration Test
+    runs-on: ubuntu-latest
+    needs: [hive-test, ef-test]
+    # Make sure this job runs even if the previous jobs failed or were skipped
+    if: ${{ always() && needs.hive-test.result != 'skipped' && needs.ef-test.result != 'skipped' }}
+    steps:
+      - name: Check if any job failed
+        run: |
+          if [ "${{ needs.hive-test.result }}" != "success" ]; then
+            echo "Job Hive Tests Check failed"
+            exit 1
+          fi
+
+          if [ "${{ needs.ef-test.result }}" != "success" ]; then
+            echo "Job EF Tests Check failed"
+            exit 1
+          fi
+
   test:
     # "Test" is a required check, don't change the name
     name: Test
