feat(l2): based feature (#2931)
**Motivation**

Initial implementation of a based rollup architecture supporting
multiple sequencers coordinated via a contract on L1. Subsequent
sequencers can synchronize through both L1 and peer-to-peer (P2P)
communication.

**Description**

- Add a new state `sequencer_state` shared across all L2 processes. This
will lead to different behaviors on whether is `Sequencing` or
`Following` for each component of the L2.
- Add two new processes for the L2 `state_updater` and `block_fetcher`: 
- `state_updater`: handles the change from `Following` to `Sequencing`
state.
- `block_fetcher`: fetches missing blocks and syncs to current L2 state.
- Add `--based` flag to the sequencer to enable the logic of changing
state. If not enabled, it will always be `Sequencing` as a centralized
sequencer.
- Add `--deploy-based-contracts` to the deployer binary to deploy the
new `OnChainProposer` and `SequencerRegistry`.
- Created `SequencerRegistry` contract that handles the batch
assignment, registering and unregistering.

**How to test**

Read the `Run Locally` section from `crates/l2/based/README.md` to run 3
nodes and register 2 of them as Sequencers.

> [!TIP]
> To enrich the review, I strongly suggest you read the documentation in
`crates/l2/based/docs`.

---------

Co-authored-by: ilitteri <ilitteri@fi.uba.ar>
Co-authored-by: Ivan Litteri <67517699+ilitteri@users.noreply.github.com>
Co-authored-by: Leandro Serra <leandro.serra@lambdaclass.com>
Co-authored-by: Avila Gastón <72628438+avilagaston9@users.noreply.github.com>
Co-authored-by: Tomás Grüner <47506558+MegaRedHand@users.noreply.github.com>

diff --git a/.github/workflows/pr-main_l2.yaml b/.github/workflows/pr-main_l2.yaml
--- a/.github/workflows/pr-main_l2.yaml
+++ b/.github/workflows/pr-main_l2.yaml
@@ -106,6 +106,81 @@ jobs:
           PROPOSER_COINBASE_ADDRESS=0x0007a881CD95B1484fca47615B64803dad620C8d cargo test l2 --release -- --nocapture --test-threads=1
           killall ethrex_prover -s SIGINT
 
+  integration-test-based:
+    name: Integration Test - Based
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+
+      - name: Rustup toolchain install
+        uses: dtolnay/rust-toolchain@stable
+
+      - name: Set up Rust cache
+        uses: Swatinem/rust-cache@v2
+
+      # also creates empty verification keys (as workflow runs with exec backend)
+      - name: Build prover
+        run: |
+          cd crates/l2
+          make build-prover
+          mkdir -p prover/zkvm/interface/sp1/out && touch prover/zkvm/interface/sp1/out/riscv32im-succinct-zkvm-vk
+
+      - name: Start L1 & Deploy contracts
+        run: |
+          cd crates/l2
+          touch .env
+          CI_ETHREX_WORKDIR=/usr/local/bin \
+          ETHREX_DEPLOYER_DEPLOY_RICH=true \
+          ETHREX_DEPLOYER_PICO_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
+          ETHREX_DEPLOYER_SP1_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
+          ETHREX_DEPLOYER_RISC0_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
+          ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS=true \
+          docker compose -f docker-compose-l2.yaml up contract_deployer
+
+      - name: Install rex
+        run: |
+          cd ..
+          rustup install nightly # Install the nightly toolchain needed by rex, change this in the future
+          rustup default nightly
+          git clone https://github.com/lambdaclass/rex.git
+          cd rex
+          make cli
+          echo "rex install successfully at $(which rex)"
+
+      - name: Register sequencer
+        run: |
+          cd crates/l2
+          SEQUENCER_REGISTRY=$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)
+          export SEQUENCER_REGISTRY
+
+          if [ -z "$SEQUENCER_REGISTRY" ]; then
+            echo "Failed to get SEQUENCER_REGISTRY from .env file"
+            exit 1
+          fi
+          rex send "$SEQUENCER_REGISTRY" 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
+          rex call "$SEQUENCER_REGISTRY" -- "leaderSequencer()"
+
+      - name: Start Sequencer
+        run: |
+          cd crates/l2
+          SEQUENCER_REGISTRY=$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)
+          export SEQUENCER_REGISTRY
+
+          CI_ETHREX_WORKDIR=/usr/local/bin \
+          ETHREX_COMMITTER_VALIDIUM=false \
+          ETHREX_WATCHER_BLOCK_DELAY=0 \
+          ETHREX_BASED=true \
+          ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY="$SEQUENCER_REGISTRY" \
+          docker compose -f docker-compose-l2.yaml up --detach ethrex_l2
+
+      - name: Run test
+        run: |
+          cd crates/l2
+          RUST_LOG=info,ethrex_prover_lib=debug make init-prover &
+          PROPOSER_COINBASE_ADDRESS=0x0007a881CD95B1484fca47615B64803dad620C8d cargo test l2 --release -- --nocapture --test-threads=1
+          killall ethrex_prover -s SIGINT
+
   state-diff-test:
     name: State Reconstruction Tests
     runs-on: ubuntu-latest
@@ -145,9 +220,9 @@ jobs:
     # "Integration Test" is a required check, don't change the name
     name: Integration Test
     runs-on: ubuntu-latest
-    needs: [integration-test, state-diff-test]
+    needs: [integration-test, state-diff-test, integration-test-based]
     # Make sure this job runs even if the previous jobs failed or were skipped
-    if: ${{ always() && needs.integration-test.result != 'skipped' && needs.state-diff-test.result != 'skipped' }}
+    if: ${{ always() && needs.integration-test.result != 'skipped' && needs.state-diff-test.result != 'skipped' && needs.integration-test-based.result != 'skipped' }}
     steps:
       - name: Check if any job failed
         run: |
@@ -158,5 +233,10 @@ jobs:
 
           if [ "${{ needs.state-diff-test.result }}" != "success" ]; then
             echo "Job State Reconstruction Tests failed"
+            exit 1
+          fi
+
+          if [ "${{ needs.integration-test-based.result }}" != "success" ]; then
+            echo "Job Integration Tests Based failed"
             exit 1
           fi
